---
- name: VPS 1 setup
  hosts: vps1
  gather_facts: false
  tasks:
    #####
    # END: docker compose up!
    #####
      # We want this to be last so that all app-specific config has been done.
    - name: Copy .env
      ansible.builtin.copy:
        dest: "/apps/.env"
        src: "../secrets/vps1.env"
        mode: "u=r,g=r,o=r"
    - name: Docker compose up! ðŸš€
      community.docker.docker_compose:
        project_src: /apps
        restarted: true
